ALTER TABLE IF EXISTS problema
ALTER COLUMN descricao SET NOT NULL;

ALTER TABLE IF EXISTS problema
ALTER COLUMN titulo SET NOT NULL;

ALTER TABLE IF EXISTS problema
ALTER COLUMN usuario_id SET NOT NULL;