ALTER TABLE IF EXISTS anotacao
ALTER COLUMN descricao SET NOT NULL;

ALTER TABLE IF EXISTS anotacao
ALTER COLUMN titulo SET NOT NULL;

ALTER TABLE IF EXISTS anotacao
ALTER COLUMN livro_id SET NOT NULL;