ALTER TABLE IF EXISTS livro
ALTER COLUMN autor SET NOT NULL;

ALTER TABLE IF EXISTS livro
ALTER COLUMN data_publicacao SET NOT NULL;

ALTER TABLE IF EXISTS livro
ALTER COLUMN editora SET NOT NULL;

ALTER TABLE IF EXISTS livro
ALTER COLUMN idioma SET NOT NULL;

ALTER TABLE IF EXISTS livro
ALTER COLUMN numero_paginas SET NOT NULL;

ALTER TABLE IF EXISTS livro
ALTER COLUMN titulo SET NOT NULL;

ALTER TABLE IF EXISTS livro
ALTER COLUMN usuario_id SET NOT NULL;
